### ISSUE TITLE
Dependencies Problem while loading a single project

### ISSUE THREAD

**Issue by wookupmaker** [nisrulz/android-examples#15]
**It's not a feature nor a bug a request to make documentation more clear.**
*You should point out that, if we are downloading a single project we also have to download the dependencies.gradle file and put it inside the parent folder of the project's folder or inside the project's folder and make a small change in project level build.gradle file*

*If you try to build a single project, for example, ActivityLifecycle toy app you will get a gradle error*
`Error:Could not read script '/home/astronaut/Downloads/dependencies.gradle' as it does not exist.`

![Screenshot](https://i.imgur.com/xsWZdle.png)

**Comment by nisrulz** [comment]
@wookupmaker good catch, I did miss that part out. I will update the readme file with the required update.

**Comment by nisrulz** [comment]
Closing as this is fixed and readme is updated.
