### ISSUE TITLE
About Gitzip download link

### ISSUE THREAD

**Issue by KinoLien** [nisrulz/android-examples#9]
Hi, i'm Gitzip repo owner, and i found your repo url from Google Analytics.
In order to make more user friendly, so I made a feature that user can click download link via parameters, like [https://kinolien.github.com/gitzip/?download=https://github.com/nisrulz/android-examples/tree/master/BuilderPattern](https://kinolien.github.com/gitzip/?download=https://github.com/nisrulz/android-examples/tree/master/BuilderPattern)

[look more info](https://github.com/KinoLien/gitzip/blob/gh-pages/README.md)

Hope this would help. :-)

**Comment by nisrulz** [comment]
Hi @KinoLien , first of all really nice work with Gitzip. Thanks to you it solves a very good problem, really appreciate your work here. 

I just checked your download via params and it looks good, really helpful. I would push an update using it today itself. Once again thank you for building Gitzip.

Cheers 😄
